### PR TITLE
Remove dependency on Sharpcompress

### PR DESCRIPTION
**Pull request by niezbop**
Implement package extraction so that there is no longer the need for the SharpCompress dll. This is done in the UnityPackageOpener.

### CODE REVIEW

**Comment by niezbop** [comment]
Okay. I just noticed that there are some mistakes left, so I'll be fixing them as well

**Comment by lacostej** [comment]
1. is there a way to remove the previously installed SharpCompress.dll using https://docs.unity3d.com/ScriptReference/AssetPostprocessor.html and finding / deleting the asset (guid = 572615ca2e9c94f84aae97a8e9b969a7)

2. how do we QA this fully? Could you make sure the new dll works with all our unity packages? It's important to have this working properly. An idea could be to have a test project that depends on all our internal/external dependencies.

**Comment by niezbop** [comment]
1. We could do it automatically, though not through the AssetPostProcessor, as it doesn't handle DLLs but rather actual assets such as Audio, Textures, Models... However, I am not convinced that we should have an automatic solution to handle SharpCompress: we are still in the early stages of Uplift and it is still identified as a beta, so getting rid of a single DLL file should be a minor adaptation. Regarding our current projects, we will have to adapt a good number of things when updating to this version of Uplift, so once again getting rid of a file in 5 projects should be fairly easy. Moreover, I feel like keeping a method that would check for the .dll presence in the future is just too much. Nonetheless, if you feel like this is important, I believe that this should be easily doable by setting an `InitializeOnLoad` and getting rid of the DLL if present.

2. Setting this up!

**Comment by lacostej** [comment]
Regarding 1. I know we don't want to necessarily let this code for this particular outdated feature (which we still use in 20+ projects, so it would have helped us there). I was interested in knowing what kind of alternatives we had to implement post import hooks for dependencies in general. 

https://docs.unity3d.com/ScriptReference/AssetPostprocessor.OnPostprocessAllAssets.html could have been the function to use. Not sure if Unity has a different mechanism for this.

**Comment by niezbop** [comment]
Ok I understand, sadly the AssetPostProcessor will not do the trick, it handles neither scripts nor dlls! An alternative could be a declaration in the initialize on load, to check if the dependency is still present, and eventually make sure it is removed.

**Pull request merged**
